name: CI for Selenium Tests

on:
  push:
    branches:
      - feature/*    # Trigger on any feature branch
      - main         # Trigger on the main branch
  pull_request:
    branches:
      - main         # Trigger on PRs to the main branch

jobs:
  test:
    runs-on: windows-latest    # Use Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'   # Specify the Java version to use
        
      - name: Install dependencies
        run: |
          choco install maven    # Install Maven using Chocolatey (Windows package manager)
          mvn install            # Install dependencies via Maven
        
      - name: Run Selenium Tests
        run: |
          mvn test   # Run your Selenium tests here
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust path to your test results
